#!/usr/bin/env python3
from __future__ import annotations
import sys, os, re, base64, hashlib, signal, platform, unicodedata
import urllib.parse, html, codecs

__version__ = "1.0.2"

# i love ascii generators i should make a tui one of those next!

LOGO = r"""
  ___ ____ ___ _  _  ___ 
 | __|_  /| __| \| |/ __|
 | _| / / | _||  ` | (__ 
 |___/___||___|_|\_|\___| 
 encode / decode anything!
"""

# transfer over functions from syt

SUPPORTS_COLOR = (
    hasattr(sys.stdout, "isatty") and sys.stdout.isatty()
    and sys.stdout.isatty()
    and os.environ.get("NO_COLOR") is None
)

def _c(code, t): return f"\033[{code}m{t}\033[0m" if SUPPORTS_COLOR else t
def bold(t): return _c("1", t)
def dim(t): return _c("2", t)
def blue(t): return _c("34", t)
def lblue(t): return _c("94", t)
def green(t): return _c("32", t)
def red(t): return _c("31", t)
def yellow(t): return _c("33", t)

def out(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

def clear_screen():
    os.system("cls" if platform.system() == "Windows" else "clear")

def _pause():
    try:
        input(dim("\n press enter to continue..."))
    except KeyboardInterrupt:
        pass

def _copy(text):
    s = platform.system()
    import subprocess, shutil as sh
    try:
        if s == "Darwin":
            subprocess.run(["pbcopy"], input=text.encode(), check=True)
            out(green("copied! :D"))
        elif s == "Linux":
            if sh.which("xclip"):
                subprocess.run(["xclip", "-selection", "clipboard"], input=text.encode(), check=True)
                out(green("copied! :D"))
            elif sh.which("xsel"):
                subprocess.run(["xsel", "--clipboard", "--input"], input=text.encode(), check=True)
                out(green("copied! :D"))
            else:
                out(red("no clipboard utility found (install xclip or xsel)!!"))
        elif s == "Windows":
            subprocess.run(["clip"], input=text.encode("utf-16"), check=True)
            out(green("copied! :D"))
    except Exception as e:
        out(yellow(f"clipboard failed: {e}"))

# please note the below two matrices have been generated by AI

COMMON_WORDS = {
    'the','be','to','of','and','a','in','that','have','it','for','not','on','with',
    'he','as','you','do','at','this','but','his','by','from','they','we','say','her',
    'she','or','an','will','my','one','all','would','there','their','what','so','up',
    'out','if','about','who','get','which','go','me','when','make','can','like','time',
    'no','just','him','know','take','people','into','year','your','good','some','could',
    'them','see','other','than','then','now','look','only','come','its','over','think',
    'also','back','after','use','two','how','our','work','first','well','way','even',
    'new','want','because','any','these','give','day','most','us','is','are','was',
    'were','been','has','had','did','said','each','hello','world','yes','ok','hi','hey',
    'test','foo','bar','example','please','thank','thanks','help','data','code',
    'name','file','path','home','user','key','value','list','type','text','info',
}

ENGLISH_BIGRAMS = {
    'th','he','in','er','an','re','on','en','at','es','ed','nd','to','or','ea',
    'ti','hi','as','te','et','ng','of','al','de','se','le','sa','si','ar','ve',
    'ra','ld','ur','ee','li','ri','ro','ic','ne','it','is','ha','nt','nc','un',
    'wa','io','me','ou','ca','ll','fi','ch','sh','la','co','ma','ow','tr','be',
}

# over :3

def _english_score(s: str) -> float:
    sl = s.lower().strip()
    if not sl:
        return 0.0
    if sum(1 for c in sl if c.isprintable()) / len(sl) < 0.85:
        return 0.0
    alpha = re.sub(r'[^a-z]', '', sl)
    if len(alpha) < 2:
        return 0.1
    bigrams = sum(1 for i in range(len(alpha) - 1) if alpha[i:i+2] in ENGLISH_BIGRAMS)
    bg_score = bigrams / max(len(alpha) - 1, 1)
    words = re.findall(r'[a-z]+', sl)
    word_bonus = sum(1 for w in words if w in COMMON_WORDS) / len(words) if words else 0.0
    return bg_score * 0.6 + word_bonus * 0.4

clear_screen()
out(blue(LOGO))
out(dim(f"version {__version__} - by zsharpminor\n"))
out("")
input1 = input(dim("enter text to get a basic english score for: "))
out("")
out(dim(f"Your English Score for '{input1}' is: {_english_score(input1)}."))
