#!/usr/bin/env python3
from __future__ import annotations
import sys, os, re, base64, hashlib, signal, platform, unicodedata
import urllib.parse, html, codecs

__version__ = "1.0.2"

# i love ascii generators i should make a tui one of those next!

LOGO = r"""
  ___ ____ ___ _  _  ___ 
 | __|_  /| __| \| |/ __|
 | _| / / | _||  ` | (__ 
 |___/___||___|_|\_|\___| 
 encode / decode anything!
"""

# transfer over functions from syt

SUPPORTS_COLOR = (
    hasattr(sys.stdout, "isatty") and sys.stdout.isatty()
    and sys.stdout.isatty()
    and os.environ.get("NO_COLOR") is None
)

def _c(code, t): return f"\033[{code}m{t}\033[0m" if SUPPORTS_COLOR else t
def bold(t): return _c("1", t)
def dim(t): return _c("2", t)
def blue(t): return _c("34", t)
def lblue(t): return _c("94", t)
def green(t): return _c("32", t)
def red(t): return _c("31", t)
def yellow(t): return _c("33", t)

def out(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

def clear_screen():
    os.system("cls" if platform.system() == "Windows" else "clear")

def _pause():
    try:
        input(dim("\n press enter to continue..."))
    except KeyboardInterrupt:
        pass

def _copy(text):
    s = platform.system()
    import subprocess, shutil as sh
    try:
        if s == "Darwin":
            subprocess.run(["pbcopy"], input=text.encode(), check=True)
            out(green("copied! :D"))
        elif s == "Linux":
            if sh.which("xclip"):
                subprocess.run(["xclip", "-selection", "clipboard"], input=text.encode(), check=True)
                out(green("copied! :D"))
            elif sh.which("xsel"):
                subprocess.run(["xsel", "--clipboard", "--input"], input=text.encode(), check=True)
                out(green("copied! :D"))
            else:
                out(red("no clipboard utility found (install xclip or xsel)!!"))
        elif s == "Windows":
            subprocess.run(["clip"], input=text.encode("utf-16"), check=True)
            out(green("copied! :D"))
    except Exception as e:
        out(yellow(f"clipboard failed: {e}"))

# please note the below two matrices have been generated by AI

COMMON_WORDS = {
    'the','be','to','of','and','a','in','that','have','it','for','not','on','with',
    'he','as','you','do','at','this','but','his','by','from','they','we','say','her',
    'she','or','an','will','my','one','all','would','there','their','what','so','up',
    'out','if','about','who','get','which','go','me','when','make','can','like','time',
    'no','just','him','know','take','people','into','year','your','good','some','could',
    'them','see','other','than','then','now','look','only','come','its','over','think',
    'also','back','after','use','two','how','our','work','first','well','way','even',
    'new','want','because','any','these','give','day','most','us','is','are','was',
    'were','been','has','had','did','said','each','hello','world','yes','ok','hi','hey',
    'test','foo','bar','example','please','thank','thanks','help','data','code',
    'name','file','path','home','user','key','value','list','type','text','info',
}

ENGLISH_BIGRAMS = {
    'th','he','in','er','an','re','on','en','at','es','ed','nd','to','or','ea',
    'ti','hi','as','te','et','ng','of','al','de','se','le','sa','si','ar','ve',
    'ra','ld','ur','ee','li','ri','ro','ic','ne','it','is','ha','nt','nc','un',
    'wa','io','me','ou','ca','ll','fi','ch','sh','la','co','ma','ow','tr','be',
}

# over :3

def _english_score(s: str) -> float:
    sl = s.lower().strip()
    if not sl:
        return 0.0
    if sum(1 for c in sl if c.isprintable()) / len(sl) < 0.85:
        return 0.0
    alpha = re.sub(r'[^a-z]', '', sl)
    if len(alpha) < 2:
        return 0.1
    bigrams = sum(1 for i in range(len(alpha) - 1) if alpha[i:i+2] in ENGLISH_BIGRAMS)
    bg_score = bigrams / max(len(alpha) - 1, 1)
    words = re.findall(r'[a-z]+', sl)
    word_bonus = sum(1 for w in words if w in COMMON_WORDS) / len(words) if words else 0.0
    return bg_score * 0.6 + word_bonus * 0.4

def _is_printable_str(s: str) -> bool:
    return bool(s) and all(c.isprintable() or c in '\n\t\r' for c in s) and bool(s.strip())

def _confidence(decoded: str, original:str) -> float:
    if not _is_printable_str(decoded):
        return 0.0
    if decoded.strip() == original.strip():
        return 0.0
    score = _english_score(decoded)
    if len(decoded) > len(original) * 3:
        score *= 0.3
    return score

# some extra functions and matrices for finding encodings (AI was used for morse braille and zalgo (the obscure ones) as well as figuring out some more interesting ciphers to go with, the remainder is my own work.)

BASE58_ALPHA = b"123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
MORSE_ENC = {
    'A':'.-','B':'-...','C':'-.-.','D':'-..','E':'.','F':'..-.','G':'--.','H':'....','I':'..','J':'.---',
    'K':'-.-','L':'.-..','M':'--','N':'-.','O':'---','P':'.--.','Q':'--.-','R':'.-.','S':'...','T':'-',
    'U':'..-','V':'...-','W':'.--','X':'-..-','Y':'-.--','Z':'--..',
    '0':'-----','1':'.----','2':'..---','3':'...--','4':'....-','5':'.....',
    '6':'-....','7':'--...','8':'---..','9':'----.',
    ' ':'/','.':'.-.-.-',',':'--..--','?':'..--..','!':'-.-.--','-':'-....-',
}
MORSE_DEC = {v: k for k, v in MORSE_ENC.items()}

# why the #ysws-fraud-fudgeudgefudge does the bacon cipher exist sob
BACON_ENC = {c: format(i, '05b').replace('0', 'A').replace('1', 'B') for i, c in enumerate("ABCDEFGHIJKLMNOPQRSTUVWXYZ")}
BACON_ENC['J'] = BACON_ENC['I']
BACON_ENC['V'] = BACON_ENC['U']
BACON_DEC = {}
for ch, code in BACON_ENC.items():
    if code not in BACON_DEC:
        BACON_DEC[code] = ch

BRAILLE_ENC = {
    'a':'⠁','b':'⠃','c':'⠉','d':'⠙','e':'⠑','f':'⠋','g':'⠛','h':'⠓','i':'⠊','j':'⠚',
    'k':'⠅','l':'⠇','m':'⠍','n':'⠝','o':'⠕','p':'⠏','q':'⠟','r':'⠗','s':'⠎','t':'⠞',
    'u':'⠥','v':'⠧','w':'⠺','x':'⠭','y':'⠽','z':'⠵',
    '0':'⠴','1':'⠂','2':'⠆','3':'⠒','4':'⠲','5':'⠢','6':'⠖','7':'⠶','8':'⠦','9':'⠔',' ':'⠀',
}
BRAILLE_DEC = {v: k for k, v in BRAILLE_ENC.items()}

NATO_ENC = {
    'A':'Alpha', 'B':'Bravo', 'C':'Charlie', 'D':'Delta', 'E':'Echo', 'F':'Foxtrot', 'G':'Golf', 'H':'Hotel',
    'I':'India', 'J':'Juliett', 'K':'Kilo', 'L':'Lima', 'M':'Mike', 'N':'November', 'O':'Oscar', 'P':'Papa',
    'Q':'Quebec', 'R':'Romeo', 'S':'Sierra', 'T':'Tango', 'U':'Uniform', 'V':'Victor', 'W':'Whiskey',
    'X':'X-ray', 'Y':'Yankee', 'Z':'Zulu',
    '0':'Zero', '1':'One', '2':'Two', '3':'Three', '4':'Four', '5':'Five', '6':'Six', '7':'Seven', '8':'Eight', '9':'Nine',
}
NATO_DEC = {v.lower(): k for k, v in NATO_ENC.items()}

# before you ask me, no, i do not know why zalgo exists.

ZALGO_UP   = ['̍','̎','̄','̅','̿','̑','̆','̐','͒','͗','͑','̇','̈','̊','͂','̓']
ZALGO_MID  = ['͉','͈','͍','͎','̣','̤','̩','̪','̻','̼','͓','͔']
ZALGO_DOWN = ['̖','̗','̘','̙','̜','̝','̞','̟','̠','̤','̥','̦']

# please note that the below list was compiled with the help of AI and is not exhaustive, but it should cover most common encodings and ciphers, as well as some more obscure ones for fun.

ENCODE_METHODS = [
    ("Base64", "base64"),
    ("Base64 URL-safe", "base64url"),
    ("Base32", "base32"),
    ("Base58", "base58"),
    ("Base85", "base85"),
    ("ASCII85", "ascii85"),
    ("URL Encode", "url"),
    ("URL Encode (full)", "url_full"),
    ("HTML Entities", "html"),
    ("Hex", "hex"),
    ("Binary", "binary"),
    ("Octal", "octal"),
    ("Caesar Cipher", "caesar"),
    ("ROT13", "rot13"),
    ("ROT47", "rot47"),
    ("Morse Code", "morse"),
    ("JWT (none alg)", "jwt"),
    ("MD5 Hash", "md5"),
    ("SHA-1 Hash", "sha1"),
    ("SHA-256 Hash", "sha256"),
    ("SHA-512 Hash", "sha512"),
    ("Unicode Escape", "unicode_escape"),
    ("Punycode", "punycode"),
    ("Quoted-Printable", "qp"),
    ("Bacon Cipher", "bacon"),
    ("Atbash Cipher", "atbash"),
    ("Reverse", "reverse"),
    ("Zalgo Text", "zalgo"),
    ("Braille", "braille"),
    ("NATO Phonetic", "nato"),
]

HASH_METHODS = {"md5", "sha1", "sha256", "sha512"}

# first actual decode method! b58 is obscure but used in crypto so I had to research quite a bit to laern how to enc/dec it.

def _b58enc(data: bytes) -> str:
    n = int.from_bytes(data, 'big')
    res = []
    while n:
        n, r = divmod(n, 58)
        res.append(BASE58_ALPHA[r:r+1].decode())
    res.reverse()
    return '1' * (len(data) - len(data.lstrip(b'\x00'))) + ''.join(res)

def _b58dec(s: str) -> bytes:
    n = 0
    for c in s:
        n = n * 58 + BASE58_ALPHA.index(c.encode())
    res = n.to_bytes((n.bit_length() + 7) // 8, 'big') if n else b''
    return b'\x00' * (len(s) - len(s.lstrip('1'))) + res

def _atbash_char(c: str) -> str:
    if c.isupper():
        return chr(90 - (ord(c) - 65))
    if c.islower():
        return chr(122 - (ord(c) - 97))
    return c

def _strip_zalgo(text: str) -> str:
    stripped = ''.join(c for c in text if unicodedata.category(c) != 'Mn')
    return stripped if stripped != text else None

# i'm sick of doing all of these manually so i'm going to use a helper

def encode(text: str, method: str, caesar_shift: int = 13) -> str:
    b = text.encode('utf-8')
    if method == "base64":
        return base64.b64encode(b).decode()
    if method == "base64url":
        return base64.urlsafe_b64encode(b).decode()
    if method == "base32":
        return base64.b32encode(b).decode()
    if method == "base58":
        return _b58enc(b)
    if method == "base85":
        return base64.b85encode(b).decode()
    if method == "ascii85":
        return base64.a85encode(b).decode()
    if method == "url":
        return urllib.parse.quote(text, safe='~-._')
    if method == "url_full":
        return urllib.parse.quote(text, safe='')
    if method == "html":
        return html.escape(text, quote=True)
    if method == "hex":
        return b.hex()
    if method == "binary":
        return ' '.join(format(x, '08b') for x in b)
    if method == "octal":
        return ' '.join(format(x, 'o') for x in b)
    if method == "caesar":
        return ''.join(chr((ord(c) - (65 if c.isupper() else 97) + caesar_shift) % 26 + (65 if c.isupper() else 97)) if c.isalpha() else c for c in text)
    if method == "rot13":
        return codecs.encode(text, 'rot_13')
    if method == "rot47":
        return ''.join(chr(33 + (ord(c) - 33 + 47) % 94) if 33 <= ord(c) <= 126 else c for c in text)
    if method == "morse":
        return ' '.join(MORSE_ENC.get(c.upper(), '?') for c in text)
    if method == "jwt":
        h = base64.urlsafe_b64encode(b'{"alg":"none","typ":"JWT"}').rstrip(b'=').decode()
        p = base64.urlsafe_b64encode(b).rstrip(b'=').decode()
        return f"{h}.{p}."
    if method == "md5":
        return hashlib.md5(b).hexdigest()
    if method == "sha1":
        return hashlib.sha1(b).hexdigest()
    if method == "sha256":
        return hashlib.sha256(b).hexdigest()
    if method == "sha512":
        return hashlib.sha512(b).hexdigest()
    if method == "unicode_escape":
        return text.encode('unicode_escape').decode('ascii')
    if method == "punycode":
        try:
            return text.encode('punnycode').decode('ascii')
        except Exception:
            return text
    if method == "qp":
        import quopri
        return quopri.encodestring(b).decode()
    if method == "bacon":
        return ' '.join(BACON_ENC.get(c.upper(), c) for c in text)
    if method == "atbash":
        return ''.join(_atbash_char(c) for c in text)
    if method == "reverse":
        return text[::-1]
    if method == "zalgo":
        import random
        res = []
        for c in text:
            res.append(c)
            for lst in [ZALGO_UP, ZALGO_MID, ZALGO_DOWN]:
                for _ in range(random.randint(0, 2)):
                    res.append(random.choice(lst))
        return ''.join(res) # so funny how zalgo is literally random crap thrown on top of text sob
    if method == "braille":
        return ''.join(BRAILLE_ENC.get(c.lower(), c) for c in text)
    if method == "nato":
        return ' '.join(NATO_ENC.get(c.upper(), c) for c in text)
    return text

# phew, that took a while! before going onto decode i needa sub it tho

# PLACEHOLDER: decode subs

clear_screen()
out(blue(LOGO))
out(dim(f"version {__version__} - by zsharpminor\n"))
input1 = input(dim("enter text to get a basic english score for: "))
out("")
out(dim(f"Your English Score for '{input1}' is: {_english_score(input1)}."))
out("")
out(blue("That encrypted in B58 is: ") + _b58enc(input1.encode()))
out(blue("And back from B58 is: ") + _b58dec(_b58enc(input1.encode())).decode())
out("")